[codestyle]
workspace_dir='/workspaces/cpp-environment/atcoder'
template_file='/workspaces/cpp-environment/main.cpp'
[compiler]
compile_command='g++ main.cpp -o main -std=c++17'
compile_only_when_diff_detected=true
[tester]
compile_before_testing=true
compile_only_when_diff_detected=true
